name: Check Lucide Imports

on: [pull_request]

jobs:
  check-imports:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/

      - name: Install ts-node
        run: npm install ts-node

      - name: Run check imports script
        run: npx ts-node --esm .github/scripts/checkLucideImports.ts