name: Svelte Check

on:
    - pull_request
    
permissions:
  pull-requests: write

jobs:
    demo:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node 22
              uses: actions/setup-node@v4
              with:
                  node-version: 22
                  registry-url: https://registry.npmjs.org/

            - name: Setup PNPM
              uses: pnpm/action-setup@v4.1.0
              with:
                  version: 10.11.1

            - name: Install
              run: pnpm install

            - name: Svelte Check
              uses: ghostdevv/svelte-check-action@v1
